### PR TITLE
Minor syntax check and cleanup with php-cs-fixer

### PR DESCRIPTION
**Pull request by hswong3i**
Minor syntax check and cleanup with php-cs-fixer:
```
php-cs-fixer fix . --level=symfony --fixers=\
align_equals,\
ordered_use,\
php_unit_construct,\
phpdoc_order,\
-no_empty_lines_after_phpdocs,\
-php_unit_strict,\
-phpdoc_no_empty_return,\
-psr0,\
-short_array_syntax
```

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This repo only follows PSR-2, so these changes arn't required.

**Comment by hswong3i** [comment]
@GrahamCampbell oh well you are correct... I checked with --level=psr2 and no change required...

BTW, such minor syntax cleanup also looks quite logical so shall we consider to merge it?

**Comment by GrahamCampbell** [comment]
Nothing to do with me. :) I was just making an observation.

**Comment by Seldaek** [comment]
I don't see why these are "cleanups" really.. it's valid syntax and this is code that pretty much never changes so the benefit of trailing commas is pretty much nil.

**Pull request closed without merging**
