### PR TITLE
PHPDoc only: Add missing tags + omit "@return null" tags

### PR DESCRIPTION
**Pull request by akilli**
Just for the sake of completeness + consistency.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This doesn't make sense.

**Comment by GrahamCampbell** [comment]
`null` means these methods CANNOT return anything. This is DIFFERENT from `void` which means anything returned is meaningless.

**Comment by akilli** [comment]
My pull request comment could have been better... but as the changes are quite minimal and PHPDoc-only, I have to admit that I was too lazy.

The additions (first commit) are quite minimal, but IMO not too senseless. Omitting the `@return null`s (second commit), albeit technically correct, is suggested for consistency reasons to PSR-7, p.e. `Psr\Http\Message\UriInterface::getPort()`, `Psr\Http\Message\ServerRequestInterface::getParsedBody()`, ... where the `return null`s seem to have a "special" or at least different meaning.

> `null` means these methods CANNOT return anything. This is DIFFERENT from `void` which means anything returned is meaningless.

I doubt that this definition is universally valid. And well... the above mentioned methods can return quite a lot :-)

**Comment by GrahamCampbell** [comment]
> I doubt that this definition is universally valid. And well... the above mentioned methods can return quite a lot :-)

That is the definition according to php.net, and it's not up for debate.

**Comment by mnapoli** [comment]
`void` doesn't exist in PHP, could you post a link that supports this:

> null means these methods CANNOT return anything. This is DIFFERENT from void which means anything returned is meaningless.

**Comment by GrahamCampbell** [comment]
http://php.net/manual/en/language.pseudo-types.php

**Comment by mnapoli** [comment]
Ha nice :) Then I would replace `@return null` with `@return void`. And also it has been discussed before (elsewhere) that a missing `@return` tags equals to `@return void`, so this PR might be moving in a good direction?

**Comment by GrahamCampbell** [comment]
But `null` is not the same as `void`. These interfaces here really do mean `null`, and not `void`.

**Comment by akilli** [comment]
> That is the definition according to php.net, and it's not up for debate.

I was rather referring to the `null` part...

> `null` means these methods CANNOT return anything.

... as this sounds weird for something like `@return array|null` or the PSR-7 methods I referred to.

Anyway, the intention of the `return null`s is quite clear and I totally agree. My changes are supposed to serve the same purpose.

**Comment by GrahamCampbell** [comment]
> ... as this sounds weird for something like @return array|null

Not it doesn't. That means it returns either an array, or nothing.

**Comment by akilli** [comment]
> Not it doesn't. That means it returns either an array, or nothing.

Which sounds somehow different than _"these methods CANNOT return anything"_ and is part of what sounds weird for me.

By the way, the PHP manual itself uses `void` on several pages where _no value_ (in fact `null`) is returned.

**Comment by GrahamCampbell** [comment]
> Which sounds somehow different than "these methods CANNOT return anything" and is part of what sounds weird for me.

No, the `|` operator means they must meet either condition.

**Comment by GrahamCampbell** [comment]
> By the way, the PHP manual itself uses void on several pages where no value (in fact null) is returned.

No, it means anything returned is meaningless. That includes no value within that set.

**Comment by akilli** [comment]
> No, the `|` operator means they must meet either condition.

I know, I have chosen the example. An union of `array` and `null` is nothing extraordinary. With your definition it sounds like _this method can return an array or CANNOT return anything_... possible, but at least a little bit weird.

As said or rather written before, the `@return null`s are fully correct and having no return statement at all or `return;` or `return null;` will actually return `null` at the end of the day, but I still see a difference between the latter and the former two.

I agreee that `@return null` is explicit, but the implementation relies on implicit language behaviour (returning `null` in case nothing is returned). And yes, you can surely discuss about how explicit `@return void` is with the definition of `void` being

> `void` as a return type means that the return value is useless.

IMO it's sufficient to express your intention. You immediately know what (not) to do when you see `@return void`...

* ...do not return anything...
* ...do not use/rely on the return value

...because it is useless anyway. Therefore it's explicit enough. Well, and you'll never see anything like `@return array|void` because it does not really make sense, does it? And something like

    /**
     * @return void
     */
    function someThing()
    {
        // ...
        return $someThing;
    }

or

    function someThing()
    {
        // ...
        
        if ($someConditionIsMet) {
            return $someThing;
        }

        // ... code with no further return statement
    }

will likely not survive a single code review.

Finally, with PHP 7 you can declare return types, but you still can not do either of

    function someThing(): null
    {
    }

or

    function someThing(): void
    {
    }

But if you could, I'd choose the second option. I know, you actually can define a class `void` and do the second, but that's not what I mean here.

**Comment by akilli** [comment]
I am closing this for now. A hopefully soon finished and accepted PSR-5 might shed some light into this, too.

**Comment by akilli** [comment]
FYI: https://wiki.php.net/rfc/void_return_type

**Comment by GrahamCampbell** [comment]
> FYI: https://wiki.php.net/rfc/void_return_type

null != void

**Comment by mnapoli** [comment]
@GrahamCampbell so?

**Pull request closed without merging**
