### PR TITLE
Bump version to `1.1.x-dev`

### PR DESCRIPTION
**Pull request by lyrixx**
1.1.0 has been released: https://github.com/php-fig/log/releases/tag/1.1.0

### CODE REVIEW

**Comment by free6k** [comment]
You created many problems for many peoples.

Problem 1                                                                                                                     
      - ps/image-optimizer 1.2.0 requires psr/log 1.0.* -> no matching package found.                                           
      - iskander-g/beboss-library dev-master requires ps/image-optimizer ^1.0 -> satisfiable by ps/image-optimizer[1.2.0].      
      - Installation request for iskander-g/beboss-library dev-master -> satisfiable by iskander-g/beboss-library[dev-master].

**Comment by Jean85** [comment]
Sorry but that's not true, and this PR is not related.

> requires psr/log 1.0.* -> no matching package found.

This means that your installation is not able to pull the older 1.0.x tagged release, which is still there and usable. Furthermore, this package (as many, many others) follows SemVer, so `ps/image-optimizer` (and anyone else) can require `^1.0` and be happy with 1.0, or 1.1.0, without issues.

**Comment by free6k** [comment]
Interesting why so happens? My deploy system working above 2 year. it crashed today. 2 issues in image/optimize. the repo issue is disabled. Wrote here.

**Comment by Jean85** [comment]
Your deploy system is probably bugged, it won't find `psr/log` 1.0.x which still exists. This PR or the 1.1.0 tag probably triggered it, but it's still a bug on your side.

**Pull request merged**
