### PR TITLE
Update PHP version requirement to 5.4.0 or higher

### PR DESCRIPTION
**Pull request by jaypatel512**
- As Traits were only available after PHP 5.4.
- See [here](http://php.net/manual/en/language.oop5.traits.php).

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
👎 This is not needed. Use of the trait is optional.

**Comment by GrahamCampbell** [comment]
Also, bumping the version constraint is pointless because composer will just resolve an earlier version of this package in order to meet the platform requirements.

**Comment by modGTB** [comment]
but not everyone is unsing composer

**Comment by xabbuh** [comment]
@modGTB But changing the `composer.json` file doesn't affect non-Composer users anyway.

**Comment by michaelcullum** [comment]
For the reasons mentioned by @GrahamCampbell I'm going to close this

**Pull request closed without merging**
