### PR TITLE
Conditional log function

### PR DESCRIPTION
**Pull request by kanariezwart**
Check first if logger is set.

### CODE REVIEW

**Comment by dragoonis** [comment]
@kanariezwart  

this is out of scope of what a "LoggerAware" trait should do.

The Aware trait is just satisfy dependency injection of the logger, not to do the logging itself. Your function should be part of the logger.

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by kanariezwart** [comment]
ok.

**Comment by manchuck** [comment]
FYI @kanariezwart Instead of using the FIG LoggerAwareTrait, you could always write your own NullLoggerAwareTrait.  Then your module can just set the null logger when the log function is called

**Comment by kanariezwart** [comment]
@manchuck thanks for thinking along. However, your solation is the same reason why I created this PR in the first place. Personally I think adding a NullLogger as default should not be necessary.

**Pull request closed without merging**
