### PR TITLE
Add LoggerSpy

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
I'm opening this PR to ask if a class like this one would be welcome in this package: http://pastebin.com/AniQf8dw

If the response if not a firm no, I can modify this PR to include a suitable version (no PHP-7, PSR-2 compliant, tests, ...) of that Spy.

Rationale behind the Spy: just a regular Spy. Facilitates testing of classes using a logger. (In my case I'm testing some logging decorators.) Most people would do this via the PHPUnit mock API, though this has a number of problems/downsides compared to using a simple test double like this spy:

* Breaks tools (rename refactoring, find usages, static code analysis) due to referring a method with a string
* Unless doing something complicated will bind to if the production code calls `log` to a specific level such as `error`.
* Requires a mocking framework, and developer knowledge of it

### CODE REVIEW

**Comment by Seldaek** [comment]
I don't see what benefit there is to having this in a standard lib tbh, because it's just a few lines of code and if that's what you need to solve a problem great but is that what otehrs need? I don't know.

**Comment by JeroenDeDauw** [comment]
Seems like a thing that is useful often enough to me. Granted, most people don't consider using a dedicated Spy instead of PHPUnits mock API. Providing it here might change that. Anyway, to me this spy falls into the same category as `NullLogger`, which is decidedly smaller.

**Comment by JeroenDeDauw** [comment]
I'm kinda disappointed this got closed; this really seems like to most sensible place to put basic test doubles for the interface. Going to create my own nano-package now, kinda silly

**Comment by michaelcullum** [comment]
To clarify, the call is @Seldaek if he wants it added. I only closed it because it had been sitting idle for a number of months and the only response was negative from Jordi.

**Comment by JeroenDeDauw** [comment]
> To clarify, the call is @Seldaek if he wants it added.

I have no objection to that if it is the case. However is it? This is in the `php-fig` org after all, so I find that mildly surprising.

**Comment by michaelcullum** [comment]
Util stuff doesn't get voted on really so precedent has dictated that it is up to the Editor. Log is a confusing one because the util stuff is in the same repo as the spec-defined interface.

**Comment by JeroenDeDauw** [comment]
This is now available as a mini-library: https://github.com/wmde/PsrLogTestDoubles

**Comment by michaelcullum** [comment]
Do you have a tweet that we could RT about that lib?

**Comment by JeroenDeDauw** [comment]
Uhm sure https://twitter.com/JeroenDeDauw/status/821862793238429696

**Pull request closed without merging**
