### PR TITLE
Replacing AbstractLogger implementation for LoggerTrait use to avoid code repetition

### PR DESCRIPTION
**Pull request by maicoqb**
Just that.
Replace all AbstractLogger implementation that already exist on LoggerTrait and use this.

### CODE REVIEW

**Comment by maicoqb** [comment]
Further, the trait implementation has more completeness, since that has the abstract log method, that the abstract class has not.

**Comment by stof** [comment]
This forces to bump the min version to PHP 5.4+, while the abstract class is currently compatible with PHP 5.3 (and used by libraries advocating PHP 5.3 support, like Symfony 2.8 for instance).
So I'm -1 on this.

The abstract class *has* the abstract method, thanks to the interface it implements

**Comment by maicoqb** [comment]
@stof, really I didn't realize that traits are 5.4+ feature. After i did perceived it, i saw that my changes was a bad idea.
But about the abstract method, the abstract truly have it, but it's not implemented.
Thanks for the reply.

**Comment by GrahamCampbell** [comment]
👎

**Comment by stof** [comment]
@maicoqb an abstract method coming from the trait or from the interface makes no difference. An abstract method is *not* implemented. This is precisely the difference between an abstract method and a concrete one: the abstract method does not have an implementation, only a signature.

**Comment by Fleshgrinder** [comment]
This should probably be closed if you do not intend to merge it. 😉

**Pull request closed without merging**
